export const YASIN_ROMAN = [
  "Yâ Sîn.",
  "Vel-Kur’ânil-Hakîm.",
  "İnneke le-mine’l-murselîn.",
  "Alâ sırâtin müstekîm.",
  "Tenzîlel-azîzir-rahîm.",
  "Li tunzira kavmen mâ unzira âbâuhum fehum gâfilûn.",
  "Lekad hakkal kavlu alâ ekserihim fehum lâ yu’minûn.",
  "İnnâ cealnâ fî a’nâkihim ağlâlen fehiye ile’l-ezkânî fehum mukmehun.",
  "Ve cealnâ min beyni eydîhim sedden ve min halfihim sedden fe ağşeynâhum fehum lâ yubsirûn.",
  "Ve sevâun aleyhim e enzertehum em lem tunzirhum lâ yu’minûn.",
  "İnnemâ tunziru menittebea’z-zikra ve haşyâr-rahmâne bi’l-ğayb; fe beşşirhu bi mağfiretin ve ecrin kerîm.",
  "İnnâ nahnu nuhyîl-mevtâ ve nektubu mâ kaddemû ve âsârehum; ve kulle şey’in ahsaynâhu fî imâmim mubîn.",
  "Vadrib lehum meselen ashâbe’l-karyeh; iz câehâ’l-murselûn.",
  "İz erselnâ ileyhimusneyn fe kezzebûhumâ fe azzezna bi sâlisin fe gâlû innâ ileykum murselûn.",
  "Kâlû mâ entum illâ beşerun mislunâ ve mâ enzelar-rahmânu min şey’in in entum illâ tekzibûn.",
  "Kâlû rabbunâ ya’lemu innâ ileykum le-murselûn.",
  "Ve mâ aleynâ illâ’l-belâğul-mübîn.",
  "Kâlû innâ tetayyarnâ bikum; le in lem tentehû le nercumennekum ve le yemessennekum minnâ azâbun elîm.",
  "Kâlû tâirukum meakum; e in zukkirtum bel entum kavmum musrifûn.",
  "Ve câe min aksa’l-medîneti raculun yes’â kâle yâ kavmit-tebiû’l-murselîn.",
  "İttebiû mel lâ yes’elukum ecran ve hum muhtedûn.",
  "Ve mâ liye lâ a’budellezî fataranî ve ileyhi turceûn.",
  "E ettehizu min dûnihî âliheten in yuridir-rahmânu bi durrin lâ tuğni annî şefâatuhum şey’en ve lâ yunkizûn.",
  "İnnî izen le-fî dalâlin mubîn.",
  "İnnî âmentu bi rabbikum fesmeûn.",
  "Kîle’d hulil-cenne. Kâle yâ leyte kavmî ya’lemûn.",
  "Bimâ ğafara li rabbî ve cealanî mine’l-mukremîn.",
  "Ve mâ enzelnâ alâ kavmihî min ba’dihî min cundin mine’s-semâi ve mâ kunnâ munzılîn.",
  "İn kânet illâ sayhaten vâhideten fe izâ hum hâmidûn.",
  "Yâ hasreten ale’l-ibâd; mâ ye’tîhim min resûlin illâ kânû bihî yestehziûn.",
  "Elem yerav kem ehleknâ kablehum minel kurûni ennehum ileyhim lâ yercîûn.",
  "Ve in kullun lemmâ cemîun ledeynâ muhdarûn.",
  "Ve âyetun lehumul ardu’l-meyte; ahyeynâhâ ve ahrece’nâ minhâ habben fe minhu ye’kulûn.",
  "Ve cealnâ fîhâ cennâtin min nahîlin ve a’nâbin ve feccernâ fîhâ mine’l-uyûn.",
  "Li ye’kulû min semerihî ve mâ amilet-hu eydîhim; efelâ yeşkürûn.",
  "Subhânellezî haleqal ezvâce küllehâ mimmâ tunbitu’l-ardu ve min enfusihim ve mimmâ lâ ya’lemûn.",
  "Ve âyetun lehumul leyli neslâhu minhün nehâra fe izâ hum muzlimûn.",
  "Ve’ş-şemsu tecrî li mustekarril lehâ; zâlike takdîrul-azîzil-alîm.",
  "Vel-kamer kaddernâhu menâzile hatta âde kel-urcûnil-kadîm.",
  "Lâ’ş-şemsu yenbeğî lehâ en tudrike’l-kamer ve le’l-leylu sâbikun-nehâr; ve kullun fî felekîn yesbehûn.",
  "Ve âyetun lehum ennâ hamelnâ zürriyyetehum fîl-fulkil meşhûn.",
  "Ve halaknâ lehum mim mislihî mâ yerkebûn.",
  "Ve in neşâ nuğrikhum fe lâ sarîha lehum ve lâ hum yunkazûn.",
  "İllâ rahmeten minnâ ve metâen ilâ hîn.",
  "Ve izâ kîle lehumut taqû mâ beyne eydîkum ve mâ halfekum leallekum turhamûn.",
  "Ve mâ te’tîhim min âyetin min âyâti rabbihim illâ kânû anhâ mu’ridîn.",
  "Ve izâ kîle lehum enfikû mimmâ razekakumullâhu kâlellezîne keferû lillezîne âmenû enut’imu men lev yeşâullâhu at’ameh; in entum illâ fî dalâlin mubîn.",
  "Ve yekûlûne metâ hâzel va’du in küntüm sâdikîn.",
  "Mâ yenzurûne illâ sayhaten vâhideten te’huzuhum ve hum yehassimûn.",
  "Fe lâ yestetîûne tavsiyeten ve lâ ilâ ehlihim yercîûn.",
  "Ve nufikha fi’s-sûri fe izâ hum minel-ecdâsi ilâ rabbihim yensilûn.",
  "Kâlû yâ veylenâ men beasenâ min merkadenâ; hâzâ mâ vaader-Rahmânu ve sadakal-murselûn.",
  "İn kânet illâ sayhaten vâhideten fe izâ hum cemîun ledeynâ muhdarûn.",
  "Fel-yevme lâ tuzlemu nefsun şey’en ve lâ tuzcavne illâ mâ küntüm ta’melûn.",
  "İnne ashabel cenneti’l-yevme fî şuğulin fâkihûn.",
  "Hum ve ezvâcuhum fî zilâlin ale’l-erâiki muttekıûn.",
  "Lehum fîhâ fâkihatun ve lehum mâ yeddeûn.",
  "Selâmun kavlen mir rabbir-rahîm.",
  "Vemtezû’l-yevme eyyühel-mücrimûn.",
  "Elem ehad ileykum yâ benî Âdeme en lâ ta’budû’ş-şeytân; innehû lekum aduvvum mubîn.",
  "Ve eni’budûnî; hâzâ sırâtun mustekîm.",
  "Ve lekad adalla minkum cibillen kesîrâ; efelâm tekûnû ta’qilûn.",
  "Hâzihî cehennemulletî küntüm tû’adûn.",
  "Islevhel-yevme bimâ küntüm tekfûrûn.",
  "El-yevme nahtimu alâ efvâhihim ve tukellimunâ eydîhim ve teşhedü ercüluhum bimâ kânû yeksibûn.",
  "Ve lev neşâ’u le temesnâ alâ a’yunihim festa baqus-sırâta fe ennâ yubsirûn.",
  "Ve lev neşâ’u le mesahnâhum alâ mekânetihim fe mestetâû mudiyyen ve lâ yercîûn.",
  "Ve men nuammirhu nünekkishu fi’l-halk; efelâ ya’qilûn.",
  "Ve mâ allemnâhu’ş-şi’ra ve mâ yenbeğî leh; in hüve illâ zikrun ve Kur’ânun mubîn.",
  "Li yunzira men kâne hayyen ve yehikkal kavlu ale’l-kâfirîn.",
  "Eve lem yerav ennâ halaknâ lehum mimmâ amilet eydînâ en’âmen fe hum lehâ mâlikûn.",
  "Ve zellelnâhâ lehum fe minhâ rekûbuhum ve minhâ ye’kulûn.",
  "Ve lehum fîhâ menâfi’u ve meşârıb; efelâ yeşkürûn.",
  "Vettehazu min dûnillâhi âliheten leallehum yunsarûn.",
  "Lâ yestetîûne nasrehum ve hum lehüm cundum muhdarûn.",
  "Fe lâ yahzunka kavluhum; innâ na’lemu mâ yusirrûne ve mâ yu’linûn.",
  "Eve lem yerâl insânu ennâ halaknâhu min nutfetin fe izâ huve hasîmum mubîn.",
  "Ve darabe lenâ meselen ve nesiyah halkah; kâle men yuhyil izâme ve hiye ramîm.",
  "Kul yuhyîhellezî enşeehâ evvele merrah; ve huve bi kulli halkin alîm.",
  "Ellezî ceale lekum mine’ş-şeceril ahdari nâran fe izâ entum minhû tûqıdûene}",
  "Eve leyse’l-lezî halakas semâvâti vel arda bi qâdirin alâ en yahluka mislehüm; belâ ve huve’l-hallâkul-alîm.",
  "İnnemâ emruhu izâ erâde şey’en en yekûle lehû kun fe yekûn.",
  "Fe subhânellezî bi yedihî melekûtu külli şey’in ve ileyhi turceûn."
]
